pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
      - check-success = "CMake"
      - check-success = "nix (macos)"
      - check-success = "nix (ubuntu)"
      - check-success = "Pip"
      - check-success = "pre-commit.ci - pr"
      - or:
        - author = pre-commit-ci[bot]
        - author = dependabot[bot]
        - approved-reviews-by = nim65s
    actions:
      merge:
